### PR TITLE
Travis

### PR DESCRIPTION
**Pull request by bbickerton**
Addresses https://github.com/mistifyio/acomm/issues/12

[Review on Reviewable](https://reviewable.io/reviews/mistifyio/acomm/13)

### CODE REVIEW

**Comment by mmlb** [comment]
Reviewed 5 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[.travis.yml, line 5 \[r2\]](https://reviewable.io:443/reviews/mistifyio/acomm/13#-KBOvlmRvc-YNHRCzHP4:-KBOvlmRvc-YNHRCzHP5:998618389) ([raw file](https://github.com/mistifyio/acomm/blob/7982ef521d64f2461b08e4bb363ac527180722d2/.travis.yml#L5)):*
add 1.6

---

*[tracker_test.go, line 82 \[r1\]](https://reviewable.io:443/reviews/mistifyio/acomm/13#-KBOvebYvRy31ZOaSYyo:-KBOvebZBKY_7p0M_PLj:2121115414) ([raw file](https://github.com/mistifyio/acomm/blob/c7f4bb382bd5251959f413476b7ae3ade26bb3e4/tracker_test.go#L82)):*
should be replaced with `case: <- time.After(5 * time.Second)`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/acomm/13)*

**Comment by TauZero** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[.travis.yml, line 5 \[r2\]](https://reviewable.io:443/reviews/mistifyio/acomm/13#-KBOvlmRvc-YNHRCzHP4:-KBOxekbRQVJgs7PsWZP:-499146009) ([raw file](https://github.com/mistifyio/acomm/blob/7982ef521d64f2461b08e4bb363ac527180722d2/.travis.yml#L5)):*
Done.

---

*[tracker_test.go, line 82 \[r1\]](https://reviewable.io:443/reviews/mistifyio/acomm/13#-KBOvebYvRy31ZOaSYyo:-KBOy2fULcYevf4wAlI_:-499146009) ([raw file](https://github.com/mistifyio/acomm/blob/c7f4bb382bd5251959f413476b7ae3ade26bb3e4/tracker_test.go#L82)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/acomm/13)*

**Comment by mmlb** [comment]
Reviewed 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 21 \[r5\]](https://reviewable.io:443/reviews/mistifyio/acomm/13#-KBPEG8oTn0fMnUNA-uV:-KBPEG8phioymb3pTAxH:405169073) ([raw file](https://github.com/mistifyio/acomm/blob/6ea40da13b400e12950ff146abad7ad7980beb19/.travis.yml#L21)):*
should this be `--enable-all --disable=errcheck ...`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/acomm/13)*

**Comment by TauZero** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 21 \[r5\]](https://reviewable.io:443/reviews/mistifyio/acomm/13#-KBPEG8oTn0fMnUNA-uV:-KBPEfZm5bBlTD-3F0K0:1879966435) ([raw file](https://github.com/mistifyio/acomm/blob/6ea40da13b400e12950ff146abad7ad7980beb19/.travis.yml#L21)):*
There is no enable all. We're testing separately, so `test` and `testify` don't need to be enabled, and we've used `goimports`, so the only thing left disabled by default is `gofmt -s`. I can enable that if you think we should.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/acomm/13)*

**Comment by mmlb** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 21 \[r5\]](https://reviewable.io:443/reviews/mistifyio/acomm/13#-KBPEG8oTn0fMnUNA-uV:-KBPFdpOiuON6uCyNK0V:984473150) ([raw file](https://github.com/mistifyio/acomm/blob/6ea40da13b400e12950ff146abad7ad7980beb19/.travis.yml#L21)):*
so weird I thought I was using it, ok then lets add`gofmt -s`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/acomm/13)*

**Comment by TauZero** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 21 \[r5\]](https://reviewable.io:443/reviews/mistifyio/acomm/13#-KBPEG8oTn0fMnUNA-uV:-KBPFbt2r8QKoh4cIJAX:478642549) ([raw file](https://github.com/mistifyio/acomm/blob/6ea40da13b400e12950ff146abad7ad7980beb19/.travis.yml#L21)):*
Actually, `gofmt` is already in the `script` part.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/acomm/13)*

**Comment by mmlb** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/acomm/13)*

**Pull request merged**
